#!/bin/bash
set -e

echo "🚀 Initializing PostgreSQL for n8n..."

ROOT_USER="${POSTGRES_USER}"
APP_USER="${POSTGRES_NON_ROOT_USER}"
APP_PASSWORD="${POSTGRES_NON_ROOT_PASSWORD}"
APP_DB="${POSTGRES_DB}"

psql -v ON_ERROR_STOP=1 --username "$ROOT_USER" --dbname postgres <<-EOSQL
-- Create application user if not exists
DO \$\$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_roles WHERE rolname = '$APP_USER'
  ) THEN
    CREATE ROLE $APP_USER LOGIN PASSWORD '$APP_PASSWORD';
  END IF;
END
\$\$;

-- Create database if not exists
DO \$\$
BEGIN
  IF NOT EXISTS (
    SELECT FROM pg_database WHERE datname = '$APP_DB'
  ) THEN
    CREATE DATABASE $APP_DB OWNER $APP_USER;
  END IF;
END
\$\$;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$ROOT_USER" --dbname "$APP_DB" <<-EOSQL
-- Extensions required by n8n v2.x
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

GRANT ALL PRIVILEGES ON DATABASE $APP_DB TO $APP_USER;

GRANT USAGE, CREATE ON SCHEMA public TO $APP_USER;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO $APP_USER;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO $APP_USER;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO $APP_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON TABLES TO $APP_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON SEQUENCES TO $APP_USER;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT ALL ON FUNCTIONS TO $APP_USER;
EOSQL

echo "✅ PostgreSQL initialized successfully for n8n"
