#!/bin/bash
set -e

echo "🚀 Initializing PostgreSQL for n8n..."

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE EXTENSION IF NOT EXISTS pgcrypto;
  CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

  CREATE SCHEMA IF NOT EXISTS public;

  GRANT ALL ON SCHEMA public TO "$POSTGRES_USER";
  GRANT ALL ON ALL TABLES IN SCHEMA public TO "$POSTGRES_USER";
  GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO "$POSTGRES_USER";

  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES TO "$POSTGRES_USER";

  ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO "$POSTGRES_USER";
EOSQL

echo "✅ PostgreSQL initialized successfully for n8n"
